name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Saluti Yongoro"
      - name: Goodbye
        run: echo "Arrivederci fratello!"
